services:
  backend:
    build: .
    expose:
      - 8080
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    build: ./postgres-docker-setup
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data: